[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Owen Leong <owenl131@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
num-integer = "0.1.44"
num = "0.1.42"
rand = "0.8.0"